### ISSUE TITLE
on starting module:sockets is not defined

### ISSUE THREAD

**Issue by luxus** [kkckkc/ZWayMqttEndpoint#1]
i tried with a remote server, a local one.. with and without auth. don't get it working...
i got a error message about socket in the beginning https://gist.github.com/luxus/6e6d0e9da65e6da6896b61bde99dc878
this message never came up again ... nothing in the logs :(
i see no connection tries on the mqtt servers

**Comment by luxus** [comment]
btw use zway in a docker on a raspberry pi

**Comment by luxus** [comment]
after some testing ... here is the error

```
[2016-05-11 10:35:06.432] [I] [core] --- Starting module ZWayMqttEndpoint
[2016-05-11 10:35:06.497] [I] [core] Notification: error (core): Cannot instantiate module: ZwayMqttEndpoint: ReferenceError: sockets is not defined
[2016-05-11 10:35:06.591] [I] [core] ReferenceError: sockets is not defined
    at new MqttClient (automation/modules/ZwayMqttEndpoint/index.js:19:21)
    at ZwayMqttEndpoint.init (automation/modules/ZwayMqttEndpoint/index.js:344:22)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:346:22)
    at AutomationController.createInstance (automation/classes/AutomationController.js:627:14)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1054:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)
```

**Comment by kkckkc** [comment]
Yes it is supposed to work - its running fine for me. Can you check which version of the zway software you are running. The error message seems to indicate that the builtin sockets module is non existent. That would suggest either me or you is running some old version. Will check more in detail later over the weekend

**Comment by luxus** [comment]
i was using a older version.. 2.1.2
i switched today to the newest but i still have the same error..
perhaps it has  something todo with the docker image.. i will investigate more ;D

**Comment by kkckkc** [comment]
Which docker image are you using?

**Comment by luxus** [comment]
https://technmeblog.wordpress.com/2015/11/28/running-z-way-on-a-raspberry-pi-in-a-docker-container/ this one..

**Comment by kkckkc** [comment]
It seems a bit too risky to try to get docker running on my only rpi - it's used for home automation and I cannot risk breaking it at the moment,

Anyhow, the sockets module is one of the standard modules in zway javascript API. I would suggest you check the existence of the file /opt/z-way-server/modules/modsockets.so and then do an 'ldd /opt/z-way-server/modules/modsockets.so' to see if it is missing some dependencies.

**Comment by luxus** [comment]
i totally understand 
```
 ldd /opt/z-way-server/modules/modsockets.so
	libwebsockets.so.5 => not found
	libcares.so.2 => not found
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6e59000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6ddd000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6db0000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6c6f000)
	/lib/ld-linux-armhf.so.3 (0x7f5b7000)
```
thats the output.
